In [3]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount = True)

Mounted at /content/gdrive


In [9]:
try:
  % cd /content/gdrive/MyDrive/AML/AML_project/
  ! git pull
except:
  % cd /content/gdrive/MyDrive/AML
  ! git clone https://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@github.com/CarlaSa/AML_project.git

/content/gdrive/MyDrive/AML/AML_project
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/CarlaSa/AML_project
   2613aaa..7bd5573  main       -> origin/main
Updating 2613aaa..7bd5573
Fast-forward
 datasets/__init__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)


In [5]:
import sys, os
py_file_location = "/content/gdrive/MyDrive/AML-Project/AML_project"
sys.path.append(os.path.abspath(py_file_location))

In [6]:
%pip install pipenv

In [7]:
!pipenv install --skip-lock --system

Installing dependencies from Pipfile...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:31


In [12]:
#%pip install 'numpy>=1.20'
import numpy as np
np.__version__

# Get Data

In [7]:
!unzip -n "/content/gdrive/MyDrive/AML/AML_project/_data/preprocessed256.zip" -d "/content"

Archive:  /content/gdrive/MyDrive/AML/AML_project/_data/preprocessed256.zip


In [10]:
from datasets import LoadDataset, CustomOutput
from datasets.custom_output import index, image_csv_index, image_csv_meta, \
    image_id, image_tensor, study_label, \
    bounding_boxes, mask, masked_image_tensor

loaded_data = LoadDataset("_data/preprocessed256", image_dtype=float,
                          label_dtype=float)

data = CustomOutput(loaded_data, image_tensor, mask)
data[42]

ImportError: ignored

In [ ]:
len(dataset)

6334

In [ ]:
# get good split of dataset -> dividable by batch_size
batch_size = 256
l = len(dataset)
x = l // (batch_size *6 )
split = [x * batch_size * 5, l - x * batch_size * 5]
split
train_set, val_set = torch.utils.data.random_split(dataset, split)

In [ ]:
dataloader_train = DataLoader(train_set, batch_size=256,
                        shuffle=True, num_workers=0)#, pin_memory = True)
dataloader_val = DataLoader(val_set, batch_size=256,
                        shuffle=True, num_workers=0, pin_memory = True)

# Get Network

In [ ]:
from unet import Unet

# Get Training

In [ ]:
from Model import get_balanced_crossentropy_loss, OurModel

In [ ]:
import torch.nn as nn
criterion = get_balanced_crossentropy_loss(train_set, verbose = True).cuda()
#criterion = nn.CrossEntropyLoss()#get_balanced_crossentropy_loss(train_set, verbose = True)
network = vanilla(use_dropout = True)
path = "/content/gdrive/MyDrive/AML project/weights"

calculate balancing vector:


  0%|          | 0/5120 [00:00<?, ?it/s]

balancing vector will be tensor([[1.8896e+00, 1.8282e+00, 1.8125e+00, 1.8125e+00],
        [2.3878e+00, 2.3574e+00, 2.3365e+00, 2.3365e+00],
        [3.8673e+01, 3.7974e+01, 3.7974e+01, 3.7974e+01],
        [3.0018e+02, 3.0018e+02, 3.0018e+02, 3.0018e+02],
        [3.1519e+03, 3.1519e+03, 3.1519e+03, 3.1519e+03],
        [6.3038e+03, 6.3038e+03, 6.3038e+03, 6.3038e+03],
        [6.3038e+03, 6.3038e+03, 6.3038e+03, 6.3038e+03],
        [6.3038e+03, 6.3038e+03, 6.3038e+03, 6.3038e+03]])


In [ ]:
for x,y in dataloader_train:
  print(y.shape)
  break

torch.Size([256, 8, 4])


In [ ]:
training = OurModel(name = "vanilla_dropout", network= network, criterion= criterion, path_dir = path, lr = 0.001, verbose = True)

In [ ]:

training.train(100, dataloader_train)

  0%|          | 0/100 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


RuntimeError: ignored

In [ ]:
for i in range(10,100,10):
  print(f"epoch {i}")
  training.load_weights(f"/vanilla_dropout_e{i}.ckpt")
  training.val(dataloader_val)

In [ ]:
! ls

'A first network.ipynb'   images        README.md	  vanilla_cnn_e10.ckpt
 carlas_dataset.py	  Model.py      trafo		  vanilla_cnn.py
 data			  -n	        Training.ipynb
'Data Plots.ipynb'	  Pipfile       transformations
 datasets		  __pycache__   utils


In [ ]:
training.load_weights(f"/vanilla_e90.ckpt")
training.val(dataloader_val)
training.load_weights(f"/vanilla_dropout_e90.ckpt")
training.val(dataloader_val)

  0%|          | 0/10 [00:00<?, ?it/s]

[[ 679    0    0    0]
 [  58 1062    2    3]
 [  23    2  406    4]
 [  29    3    3  154]]


  0%|          | 0/10 [00:00<?, ?it/s]

[[ 679    0    0    0]
 [  58 1057    6    4]
 [  23   18  384   10]
 [  29   20   16  124]]
