In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

# Get Data

In [9]:
from datasets.image_dataset import ImageDataset, UniformImageDataset
from datasets.study_dataset import StudyDataset
from datasets.masked_image_study_labeled_dataset import MaskedImageStudyLabeledDataset

from datasets.io import LoadDataset
dataset = LoadDataset("_data/masked256", label_dtype=bool, image_dtype = float)

In [10]:
# get good split of dataset -> dividable by batch_size
batch_size = 64
l = len(dataset)
x = l // (batch_size *6 )
split = [x * batch_size * 5, l - x * batch_size * 5]
split
train_set, val_set = torch.utils.data.random_split(dataset, split)

In [11]:
dataloader_train = DataLoader(train_set, batch_size=64,
                        shuffle=True, num_workers=0)
dataloader_val = DataLoader(val_set, batch_size=64,
                        shuffle=True, num_workers=0)

# Get Network

In [12]:
from vanilla_cnn import vanilla

# Get Training

In [13]:
from Model import get_balanced_crossentropy_loss, OurModel

In [14]:
criterion = get_balanced_crossentropy_loss(train_set, verbose = True)
network = vanilla()
path = "./weights"

calculate balancing vector:


  0%|          | 0/10240 [00:00<?, ?it/s]

balancing vector will be tensor([0.9159, 0.5274, 1.4105, 3.2990])


In [15]:
network = vanilla()

In [16]:
training = OurModel(name = "vanilla", network= network, criterion= criterion, path_dir = path)

In [18]:
training.train(100, dataloader_train)

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

  0%|          | 0/160 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [19]:
training.val(dataloader_val)

  0%|          | 0/38 [00:00<?, ?it/s]

[[   0  677    0    0]
 [   0 1160    0    0]
 [   0  401    0    0]
 [   0  190    0    0]]


In [21]:
network

vanilla(
  (conv1): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv3): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1))
  (pool3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv4): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  (pool4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv5): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=9216, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=4, bias=True)
)